{"name": "test_dodawania[2-6]", "status": "failed", "statusDetails": {"message": "AssertionError: Suma dwóch takich samych składników powinna być równa 4\nassert 6 == (2 + 2)", "trace": "skladnik = 2, suma = 6\n\n    @pytest.mark.parametrize(\"skladnik, suma\", [(5,8),(2,6)])\n    def test_dodawania(skladnik,suma):\n>       assert suma == skladnik + skladnik, \"Suma dwóch takich samych składników powinna być równa \" + str(skladnik+skladnik)\nE       AssertionError: Suma dwóch takich samych składników powinna być równa 4\nE       assert 6 == (2 + 2)\n\nTests\\for_test.py:42: AssertionError"}, "parameters": [{"name": "skladnik", "value": "2"}, {"name": "suma", "value": "6"}], "start": 1637093539273, "stop": 1637093539273, "uuid": "e69e6236-1cf2-4eaf-8c8b-84bee9843d7f", "historyId": "5abbf7623aaba15557e497d4413486bd", "testCaseId": "f4546c1ddbd651cbfa15f886ac2bc154", "fullName": "Tests.for_test#test_dodawania", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "for_test"}, {"name": "host", "value": "Karol-Komputer"}, {"name": "thread", "value": "9080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.for_test"}]}